export const dummyTasks = [
  // Tasks for u1
  {
    id: 't1',
    userId: 'u1',
    title: 'Master Angular',
    summary: 'Learn all the features of Angular & how to apply them.',
    dueDate: '2025-12-31',
    isDone: false,
  },
  {
    id: 't2',
    userId: 'u1',
    title: 'Fix routing bug',
    summary: 'Resolve issue with /dashboard navigation.',
    dueDate: '2024-07-02',
    isDone: false,
  },
  {
    id: 't3',
    userId: 'u1',
    title: 'Improve mobile layout',
    summary: 'Make the dashboard fully responsive on mobile.',
    dueDate: '2024-07-10',
    isDone: true,
  },
  {
    id: 't4',
    userId: 'u1',
    title: 'Refactor Auth Service',
    summary: 'Simplify and improve authentication service.',
    dueDate: '2024-07-15',
    isDone: false,
  },
  {
    id: 't5',
    userId: 'u1',
    title: 'Write unit tests',
    summary: 'Cover login and register components with tests.',
    dueDate: '2024-07-20',
    isDone: false,
  },
  {
    id: 't6',
    userId: 'u1',
    title: 'Review pull requests',
    summary: 'Code review for team submissions on GitHub.',
    dueDate: '2024-07-25',
    isDone: false,
  },

  // Tasks for u2
  {
    id: 't7',
    userId: 'u2',
    title: 'Design homepage',
    summary: 'Create a homepage layout with branding elements.',
    dueDate: '2024-06-25',
    isDone: false,
  },
  {
    id: 't8',
    userId: 'u2',
    title: 'Style login form',
    summary: 'Style and animate login form UI.',
    dueDate: '2024-06-30',
    isDone: false,
  },
  {
    id: 't9',
    userId: 'u2',
    title: 'Build user profile page',
    summary: 'Design and implement user profile view.',
    dueDate: '2024-07-03',
    isDone: false,
  },
  {
    id: 't10',
    userId: 'u2',
    title: 'Fix navbar bugs',
    summary: 'Resolve alignment issues in nav menu.',
    dueDate: '2024-07-06',
    isDone: false,
  },
  {
    id: 't11',
    userId: 'u2',
    title: 'Add dark mode toggle',
    summary: 'Support theme switching between light and dark.',
    dueDate: '2024-07-09',
    isDone: false,
  },
  {
    id: 't12',
    userId: 'u2',
    title: 'Accessibility improvements',
    summary: 'Make buttons and forms more screen-reader friendly.',
    dueDate: '2024-07-12',
    isDone: false,
  },

  // Tasks for u3
  {
    id: 't13',
    userId: 'u3',
    title: 'Build first prototype',
    summary: 'Build a prototype of the online shop.',
    dueDate: '2024-05-31',
    isDone: false,
  },
  {
    id: 't14',
    userId: 'u3',
    title: 'Prepare issue template',
    summary: 'Create a template for bug reporting.',
    dueDate: '2024-06-15',
    isDone: false,
  },
  {
    id: 't15',
    userId: 'u3',
    title: 'Implement cart functionality',
    summary: 'Allow users to add/remove items from cart.',
    dueDate: '2024-07-01',
    isDone: false,
  },
  {
    id: 't16',
    userId: 'u3',
    title: 'Add search filter',
    summary: 'Enable search and category filtering.',
    dueDate: '2024-07-05',
    isDone: false,
  },
  {
    id: 't17',
    userId: 'u3',
    title: 'Fix product image zoom',
    summary: 'Improve zoom and fullscreen image viewer.',
    dueDate: '2024-07-10',
    isDone: false,
  },
  {
    id: 't18',
    userId: 'u3',
    title: 'Write checkout tests',
    summary: 'Test all checkout edge cases.',
    dueDate: '2024-07-15',
    isDone: false,
  },

  // Tasks for u4
  {
    id: 't19',
    userId: 'u4',
    title: 'Write API docs',
    summary: 'Document user and product endpoints.',
    dueDate: '2024-07-10',
    isDone: false,
  },
  {
    id: 't20',
    userId: 'u4',
    title: 'Integrate payment system',
    summary: 'Add and test Stripe integration.',
    dueDate: '2024-07-18',
    isDone: false,
  },
  {
    id: 't21',
    userId: 'u4',
    title: 'Secure admin panel',
    summary: 'Implement route guards and RBAC.',
    dueDate: '2024-07-21',
    isDone: false,
  },
  {
    id: 't22',
    userId: 'u4',
    title: 'Optimize API calls',
    summary: 'Debounce & cache repeated requests.',
    dueDate: '2024-07-25',
    isDone: false,
  },
  {
    id: 't23',
    userId: 'u4',
    title: 'Handle API errors globally',
    summary: 'Create interceptor for error messages.',
    dueDate: '2024-07-28',
    isDone: false,
  },
  {
    id: 't24',
    userId: 'u4',
    title: 'Add loading spinners',
    summary: 'Show loading indicators for HTTP requests.',
    dueDate: '2024-07-30',
    isDone: false,
  },

  // Tasks for u5
  {
    id: 't25',
    userId: 'u5',
    title: 'Optimize images',
    summary: 'Compress and lazy-load homepage images.',
    dueDate: '2024-07-05',
    isDone: false,
  },
  {
    id: 't26',
    userId: 'u5',
    title: 'Audit accessibility',
    summary: 'Fix issues from accessibility audit.',
    dueDate: '2024-07-12',
    isDone: false,
  },
  {
    id: 't27',
    userId: 'u5',
    title: 'Add sitemap.xml',
    summary: 'Help search engines crawl the site.',
    dueDate: '2024-07-13',
    isDone: false,
  },
  {
    id: 't28',
    userId: 'u5',
    title: 'Improve Core Web Vitals',
    summary: 'Reduce CLS, LCP, FID.',
    dueDate: '2024-07-16',
    isDone: false,
  },
  {
    id: 't29',
    userId: 'u5',
    title: 'Implement 404 page',
    summary: 'Custom not-found route and page.',
    dueDate: '2024-07-18',
    isDone: false,
  },
  {
    id: 't30',
    userId: 'u5',
    title: 'Add meta tags for SEO',
    summary: 'Add OpenGraph and Twitter meta tags.',
    dueDate: '2024-07-20',
    isDone: false,
  },

  // Tasks for u6
  {
    id: 't31',
    userId: 'u6',
    title: 'Research deployment options',
    summary: 'Compare Firebase, Netlify, Vercel.',
    dueDate: '2024-07-20',
    isDone: false,
  },
  {
    id: 't32',
    userId: 'u6',
    title: 'Set up CI/CD pipeline',
    summary: 'Configure GitHub Actions.',
    dueDate: '2024-07-28',
    isDone: false,
  },
  {
    id: 't33',
    userId: 'u6',
    title: 'Automate versioning',
    summary: 'Use semantic-release for tagging builds.',
    dueDate: '2024-07-30',
    isDone: false,
  },
  {
    id: 't34',
    userId: 'u6',
    title: 'Create changelog generator',
    summary: 'Auto-generate changelog from commits.',
    dueDate: '2024-08-01',
    isDone: false,
  },
  {
    id: 't35',
    userId: 'u6',
    title: 'Write deployment scripts',
    summary: 'Automate Firebase + CDN push.',
    dueDate: '2024-08-03',
    isDone: false,
  },
  {
    id: 't36',
    userId: 'u6',
    title: 'Monitor production uptime',
    summary: 'Set up uptime monitoring tools.',
    dueDate: '2024-08-05',
    isDone: false,
  },
];
